// <auto-generated />
using System;
using BloginSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BloginSystem.Migrations
{
    [DbContext(typeof(BlogingContext))]
    [Migration("20211228130221_BlogingDB")]
    partial class BlogingDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BloginSystem.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Authorname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("blogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Authorname = "Suny",
                            BlogBody = "abcdefg",
                            CreatedAt = new DateTime(2021, 12, 28, 19, 2, 21, 79, DateTimeKind.Local).AddTicks(2634),
                            Title = "Blog post title"
                        },
                        new
                        {
                            Id = 2,
                            Authorname = "Suny",
                            BlogBody = "abcdefg",
                            CreatedAt = new DateTime(2021, 12, 28, 19, 2, 21, 80, DateTimeKind.Local).AddTicks(3050),
                            Title = "Blog post title"
                        },
                        new
                        {
                            Id = 3,
                            Authorname = "Suny",
                            BlogBody = "abcdefg",
                            CreatedAt = new DateTime(2021, 12, 28, 19, 2, 21, 80, DateTimeKind.Local).AddTicks(3071),
                            Title = "Blog post title"
                        },
                        new
                        {
                            Id = 4,
                            Authorname = "Suny",
                            BlogBody = "abcdefg",
                            CreatedAt = new DateTime(2021, 12, 28, 19, 2, 21, 80, DateTimeKind.Local).AddTicks(3075),
                            Title = "Blog post title"
                        },
                        new
                        {
                            Id = 5,
                            Authorname = "Suny",
                            BlogBody = "abcdefg",
                            CreatedAt = new DateTime(2021, 12, 28, 19, 2, 21, 80, DateTimeKind.Local).AddTicks(3076),
                            Title = "Blog post title"
                        });
                });

            modelBuilder.Entity("BloginSystem.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
